# As principais operações que vamos aprender são o Fatiamento de String, Análise com len(), count(), find(), transformações com replace(), upper(), lower(), capitalize(), title(), strip(), junção com join().
frase=("  Que a Força Esteja Com Você!  ")
print(frase)
print(frase[13:31])
print(frase[13:31:2])
print(frase[:5])
print(frase[9::3])
print(len(frase))
print(frase.find('força'))
print(frase.count("o"))
print(frase.find("sabre de luz"))
print("python"in frase )
print(frase.replace("força","energia viva"))
print(frase.upper())
print(frase.lower())
print(frase.capitalize())
print(frase.title())
print(frase.strip())
print(frase.rstrip())
print(frase.lstrip())
print(frase.split())
print("-".join(frase))